[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "wp-enlighten"
version = "4.2.14"

dependencies = [
    "wasatch",
    "numpy",
    "ai_edge_litert",
    "PySide6",
    "pygtail ",
    "pyusb ",
    "pefile ",
    "pywavelets ",
    "superman ",
    "pyqtgraph ",
    "libusb ",
    "boto3 ",
    "bleak ",
    "pyftdi ",
    "adafruit-blinka",
    "SPyC_Writer",
    "crcmod",
    "pandas",
    "pexpect",
    "pip",
    "psutil",
    "pytest",
    "scipy",
    "xlwt",
    "qimage2ndarray",
    "2to3",
    "matplotlib",
    "pyserial",
    "colour-science",
    "colour",

    "pywin32   ; sys_platform == 'win32'",
    "ids_peak  ; sys_platform == 'win32'",
    "seabreeze ; sys_platform == 'win32'",
]

authors = [
  { name="Mark Zieg", email="mzieg@wasatchphotonics.com" },
]

description = "A GUI to control and collect data from Wasatch Photonics spectrometers"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",

]
license = "MIT"
license-files = ["LICEN[CS]E*"]

keywords = ["wasatch", "wasatchphotonics", "spectrometer", "raman"]


[project.gui-scripts]
enlighten = "wp_enlighten.app:main"

[project.urls]
Documentation = "https://wasatchphotonics.com/enlighten"
Homepage = "https://wasatchphotonics.com/enlighten"
Repository = "https://github.com/WasatchPhotonics/ENLIGHTEN.git"
Issues = "https://github.com/WasatchPhotonics/ENLIGHTEN/issues"
Changelog = "https://github.com/WasatchPhotonics/ENLIGHTEN/blob/master/CHANGELOG.md"
